# Dimentionality Reduction
- used to reduce number of feature
- two types: Feature Selection & Feature Extraction  

Advantages:  
- less space is required
- less computation time
- takes care of multicollinearity by removing redundant features(e.g: kg & gms)



## Common Feature Selection Techiniques
By only keeping the most relevant variables from the original dataset

- Backward Feature Elimination (Start removing one variable each time and check performance)
- Forward Feature Selection (Start with one variable and see which is best)
- Random Forest (comes packaged with in-built feature importance)



## Common Feature Extraction Techiniques

### 1. Principal Component Analysis (PCA)

remove feature that explains less % of variance


In [21]:
#Take the full code from Logistic Regression and modify the import dataset X & y to include more features
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Data\Dimensionality\Wine.csv')
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

X = X.astype(float)
y = y.astype(float)

# Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Perform Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Applying PCA
from sklearn.decomposition import PCA
#pca = PCA(n_components = None), In case to check the variance of each independent variable
pca = PCA(n_components = 3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)



[0.37281068 0.18739996 0.10801208]


In [16]:
# Fitting Logistic Regression to the Training set
#lbfgs = Limited-memory BFGS  It is a popular algorithm for parameter estimation in machine learning.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='auto') 
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[15  1  0]
 [ 0 21  0]
 [ 0  0  8]]


### 2. Linear Discriminant Analysis <a href="https://medium.com/machine-learning-researcher/dimensionality-reduction-pca-and-lda-6be91734f567">(LDA)</a>


In [22]:
#Take the full code from Logistic Regression and modify the import dataset X & y to include more features
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Data\Dimensionality\Wine.csv')
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

X = X.astype(float)
y = y.astype(float)

# Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Perform Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Applying LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = None)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)
explained_variance = lda.explained_variance_ratio_
print(explained_variance)


[0.74784132 0.25215868]


## 3. Kernel PCA

In [ ]:
# Applying Kernel PCA
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components = 2, kernel = 'rbf')
X_train = kpca.fit_transform(X_train)
X_test = kpca.transform(X_test)